### ISSUE TITLE
Use simple readline prompt for the password on registration

### ISSUE THREAD

**Issue by hmngwy** [hmngwy/weblog.sh#10]

**Comment by hmngwy** [comment]
Could be unnecessary, since #12 fixed.

**Comment by pscollins** [comment]
A thought --- you could let users register directly with their ssh keys and cut out the password mechanism entirely, since it seems to be causing some issues. 

This requires everyone to have an ssh key set up, but it's a CLI blog app, after all, it's not targeting users who can't make their own. It also means that you lose access forever if you lose your SSH key, but personally I reset passwords that I forget much more often than I make a new public key.

**Comment by marksteve** [comment]
@pscollins :+1: A curl command would do:

``` sh
curl -F "usename=username" -F "public_key=@~/.ssh/id_rsa.pub" https://weblog.sh
```

**Comment by hmngwy** [comment]
@pscollins definitely considering that, the registration UI is having issues with some term setups, and I just want to get rid of it now.

@marksteve hmm, wondering why you suggest this? Just curious. Cause I think I can just wire up registration with the existing key setting command `ssh walt@weblog.sh key $(cat ~/.ssh/id_rsa.pub)`.

**Comment by marksteve** [comment]
@hmngwy no ident ssh access scares me :P Though yeah, the least deps the better. I actually tried running that command first before registering because I thought that would already register me.

**Comment by hmngwy** [comment]
@marksteve I see, it's a custom SSH server and the users won't be allowed to do anything beyond what is defined. I think it's relatively safer than a real no ident shell access.

**Comment by hmngwy** [comment]
ac4e6c8 pushed to live

**Comment by marksteve** [comment]
Nice
