### ISSUE TITLE
Invisible text on registering

### ISSUE THREAD

**Issue by jaapz** [hmngwy/weblog.sh#12]
When I try to register using

```
$ ssh jaapz@weblog.sh -p2222
```

I see the cursor move as if characters are printed, but the characters themselves are not visible. Looks like the text is black on a black background.

I tried this in `st` and `xterm`, using both `zsh` and `bash`, all with the same results.

**Comment by hmngwy** [comment]
Hello @jaapz, the problem has been known since last night, and I sort of forgot to make the issue. Thanks. 

Anyway, it turned out to be some terminal specific code that is making the text invisible.

This has been fixed here: 5a79eae, but I have only tested on xterm+bash+mac terminal, if you no longer see this, feel free to close the issue. :)

Edit: oh, just realized you were one of the first to report the issue on reddit, thanks!

**Comment by hmngwy** [comment]
btw @jaapz, little bit off-topic, if you have problem logging in with a password, it's because when you registered there was an issue with password processing.

Let me know if you want to recover your username.

**Comment by jaapz** [comment]
@hmngwy ah yes, I tried logging in, but I couldn't log in after registering. Was wondering what that was about. Yeah, would really like to recover my username :+1: (it's also jaapz)

**Comment by hmngwy** [comment]
Ok try re-registering now. Thanks @jaapz!
