### ISSUE TITLE
"Permission denied" on weblog write

### ISSUE THREAD

**Issue by mattbk** [hmngwy/weblog.sh#2]
> matt@matt-VirtualBox:~$ weblog write 
> /home/matt/./weblog.sh: line 217: /home/matt/.weblog/workspace: Permission denied
> ###### ################################################################## 100.0%
> 
> Did not save, title missing.
> [local] → backup saved as "~/.weblog/history/2015-10-27-15-35-37"

I tried expanding read/write to the `.weblog` folder and to the `workspace` file, but no change.

Ubuntu 14.04 in VirtualBox.

**Comment by hmngwy** [comment]
Given you already added the write perms, not sure what would be causing that. Though if it was able to create .weblog/workspace, it should be able to write on it. 

Did you let it create .weblog/workspace or did you `touch` it?

I'll try to set up an Ubuntu machine to test, I'll let you know. Thanks

**Comment by hmngwy** [comment]
I think I found it. The script uses $EDITOR to launch the system's text editor, but in Ubuntu this is unset, and I didn't know that because I'm dumb, hehe. Ubuntu uses the command `editor` to launch its default-set editor.

If you know of a cross-platform way to launch the default editor, I'm all ears, I'm relatively new to bash scripting.

**Comment by hmngwy** [comment]
I think it should just: 
1. check $EDITOR, if not found then
2. check editor via `which editor`, if not found then
3. just launch nano, everyone's got nano

**Comment by mattbk** [comment]
Confirm it works.  Cool!
